services:
  - type: web
    name: lume
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXT_PUBLIC_BASE_PATH
        value: ""
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
